#pragma config(Sensor, S1,     Ltouch,         sensorTouch)
#pragma config(Sensor, S2,     Rtouch,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int bump_state = 0; // robot's bumped state

/*
 * The main thread for the sender brick. It only gets touch sensor values and
 * sends them every 100 milliseconds.
 */
task main() {
  while (true) {
  	if ((SensorValue(Ltouch) == 0) && (SensorValue(Rtouch) == 1)) { // right bumped
	    sendMessage(1);
	    bump_state = 1;
   	} else if ((SensorValue(Ltouch) == 1) && (SensorValue(Rtouch) == 0)) { // left bumped
   		sendMessage(2);
   		bump_state = 2;
  	} else if ((SensorValue(Ltouch) == 1) && (SensorValue(Rtouch) == 1)) { // both bumped
  		sendMessage(3);
  		bump_state = 3;
    } else {
    	sendMessage(0);
    	bump_state = 0;
    }

    alive();
    displayCenteredTextLine(3, "Bump State: %d", bump_state);
    wait1Msec(100);
  }
}
